import React from 'react';

import MultiSelector, { PropTypes as MultiSelectorPropTypes } from 'components/common/TempSelector';

const BOOK_CATEGORY = {
  CAM: '재경관리사',
  AM: '회계관리1급',
} as const;

const CAM_CHAPTER_CATEGORY = {
  TAX_AND_NATIONAL_TAX: '1. 조세총론 / 국세기본법',
  CORPORATE_TAX: '2. 법인세법',
  INCOME_TAX: '3. 소득세',
  VAT: '4. 부가가치세법',
} as const;

const AM_CHAPTER_CATEGORY = {
  GO: '1. 총론',
  CORPORATE_TAX: '2. 법인세',
  INCOME_TAX_AND_WITHHOLDING_TAX: '3. 소득세 / 원천징수 실무',
  VAT_AND_TAX_BILL: '4. 부가가치세 / 세금계산서 실무',
};

const BOOKS: MultiSelectorPropTypes['books'] = [
  { name: BOOK_CATEGORY.CAM, value: '0' },
  { name: BOOK_CATEGORY.AM, value: '1' },
];

const CHAPTER: MultiSelectorPropTypes['chapters'] = [
  { name: CAM_CHAPTER_CATEGORY.TAX_AND_NATIONAL_TAX, book: BOOK_CATEGORY.CAM, value: '0' },
  { name: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, book: BOOK_CATEGORY.CAM, value: '1' },
  { name: CAM_CHAPTER_CATEGORY.INCOME_TAX, book: BOOK_CATEGORY.CAM, value: '2' },
  { name: CAM_CHAPTER_CATEGORY.VAT, book: BOOK_CATEGORY.CAM, value: '3' },
  { name: AM_CHAPTER_CATEGORY.GO, book: BOOK_CATEGORY.AM, value: '4' },
  { name: AM_CHAPTER_CATEGORY.CORPORATE_TAX, book: BOOK_CATEGORY.AM, value: '5' },
  { name: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, book: BOOK_CATEGORY.AM, value: '6' },
  { name: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, book: BOOK_CATEGORY.AM, value: '7' },
];

const TOPIC: MultiSelectorPropTypes['topics'] = [
  { name: '1. 조세의 개념과 분류', chapter: CAM_CHAPTER_CATEGORY.TAX_AND_NATIONAL_TAX, value: '0' },
  { name: '2. 조세법의 기본원칙', chapter: CAM_CHAPTER_CATEGORY.TAX_AND_NATIONAL_TAX, value: '1' },
  { name: '3. 총설', chapter: CAM_CHAPTER_CATEGORY.TAX_AND_NATIONAL_TAX, value: '2' },
  { name: '4. 국세부과의 원칙', chapter: CAM_CHAPTER_CATEGORY.TAX_AND_NATIONAL_TAX, value: '3' },
  { name: '5. 세법적용의 원칙', chapter: CAM_CHAPTER_CATEGORY.TAX_AND_NATIONAL_TAX, value: '4' },
  { name: '6. 과세요건', chapter: CAM_CHAPTER_CATEGORY.TAX_AND_NATIONAL_TAX, value: '5' },
  { name: '1. 총설', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '6' },
  { name: '2. 각 사업연도 소득에 대한 법인세', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '7' },
  { name: '3. 익금의 계산', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '8' },
  { name: '4. 손금의 계산', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '9' },
  { name: '5. 손익의 귀속', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '10' },
  { name: '6. 감가상각비의 손금불산입', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '11' },
  { name: '7. 기부금의 손금불산입', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '12' },
  { name: '8. 접대비의 손금불산입', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '13' },
  { name: '9. 지급이자의 손금불산입', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '14' },
  { name: '10 충당금의 손금산입', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '15' },
  { name: '11. 준비금의 손금산입', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '16' },
  { name: '12. 부당행위계산부인', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '17' },
  { name: '13. 과세표준과 세액의 계산', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '18' },
  { name: '14. 법인세의 신고와 납부', chapter: CAM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '19' },
  { name: '1. 총설', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '20' },
  { name: '2. 소득세의 계산구조', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '21' },
  { name: '3. 금융소득', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '22' },
  { name: '4. 사업소득', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '23' },
  { name: '5. 근로소득', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '24' },
  { name: '6. 연금소득, 기타소득', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '25' },
  { name: '7. 종합소득금액의 계산', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '26' },
  { name: '8. 종합소득과세표준 및 세액의 계산', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '27' },
  { name: '9. 세액공제, 감면', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '28' },
  { name: '10. 퇴직소득세', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '29' },
  { name: '11. 원천징수', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '30' },
  { name: '12. 연말정산', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '31' },
  { name: '13. 양도소득세', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '32' },
  { name: '14. 신고납부 및 결정과 징수', chapter: CAM_CHAPTER_CATEGORY.INCOME_TAX, value: '33' },
  { name: '1. 부가가치세의 계산구조', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '34' },
  { name: '2. 부가가치세의 의의', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '35' },
  { name: '3. 납부의무자', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '36' },
  { name: '4. 과세기간', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '37' },
  { name: '5. 납세지', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '38' },
  { name: '6. 부가가치세의 과세대상거래', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '39' },
  { name: '7. 재화와 용역의 공급시기', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '40' },
  { name: '8. 영세율과 면세', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '41' },
  { name: '9. 과세표준과 매출세액의 계산', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '42' },
  { name: '10. 매입세액의 계산', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '43' },
  { name: '11. 세금계산서 실무', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '44' },
  { name: '12. 부가가치세의 신고, 납부', chapter: CAM_CHAPTER_CATEGORY.VAT, value: '45' },
  { name: '1. 조세의 개요', chapter: AM_CHAPTER_CATEGORY.GO, value: '46' },
  { name: '2. 조세의 분류', chapter: AM_CHAPTER_CATEGORY.GO, value: '47' },
  { name: '3. 납세의무의 확정방법', chapter: AM_CHAPTER_CATEGORY.GO, value: '48' },
  { name: '4. 조세의 기본개념', chapter: AM_CHAPTER_CATEGORY.GO, value: '49' },
  { name: '5. 국세부과의 원칙', chapter: AM_CHAPTER_CATEGORY.GO, value: '50' },
  { name: '6. 가산세의 부과', chapter: AM_CHAPTER_CATEGORY.GO, value: '51' },
  { name: '7. 주요 국세의 개요', chapter: AM_CHAPTER_CATEGORY.GO, value: '52' },
  { name: '8. 주요 지방세의 개요', chapter: AM_CHAPTER_CATEGORY.GO, value: '53' },
  { name: '1. 법인세 총설', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '54' },
  { name: '2. 각사업연도소득에 대한 법인세 총설', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '55' },
  { name: '3. 손익의 귀속시기 및 자산의 취득가액', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '56' },
  { name: '4. 익금 및 익금불산입', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '57' },
  { name: '5. 손금 및 손금불산입', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '58' },
  { name: '6. 재고자산 및 유가증권의 평가', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '59' },
  { name: '7. 유.무형자산의 감가상각', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '60' },
  { name: '8. 접대비와 기부금', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '61' },
  { name: '9. 퇴직급여충당금과 대손충당금', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '62' },
  { name: '10. 준비금', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '63' },
  { name: '11. 지급이자 손금불산입', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '64' },
  { name: '12. 부당행위계산부인', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '65' },
  { name: '13. 법인세 과세표준의 계산', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '66' },
  { name: '14. 법인세 산출세액의 계산', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '67' },
  { name: '15. 차감납부할 세액의 계산', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '68' },
  { name: '16. 법인세 신고 및 납부', chapter: AM_CHAPTER_CATEGORY.CORPORATE_TAX, value: '69' },
  { name: '1. 소득세의 의의', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '70' },
  { name: '2. 납세의무자', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '71' },
  { name: '3. 과세대상소득', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '72' },
  { name: '4. 과세기간', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '73' },
  { name: '5. 납세지', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '74' },
  { name: '6. 소득세의 계산구조', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '75' },
  { name: '7. 이자소득과 배당소득', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '76' },
  { name: '8. 사업소득', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '77' },
  { name: '9. 근로소득', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '78' },
  { name: '10. 연금소득 및 기타소득', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '79' },
  { name: '11. 종합소득 과세표준계산 및 세액계산', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '80' },
  { name: '12. 퇴직소득 및 양도소득', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '81' },
  { name: '13. 신고.납부와 징수', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '82' },
  { name: '14. 연말정산의 의의', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '83' },
  { name: '15. 원천징수의 의의', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '84' },
  { name: '16. 원천징수 실무', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '85' },
  { name: '17. 원천징수이행상황신고서', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '86' },
  { name: '18. 근로소득의 개념', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '87' },
  { name: '19. 근로소득에 대한 원천징수와 연말정산의 관계', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '88' },
  { name: '20. 간이세액표', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '89' },
  { name: '21. 상여지급시 원천징수세액', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '90' },
  { name: '22. 일용근로자의 원천징수', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '91' },
  { name: '23. 근로소득 원천징수세액의 납부방법', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '92' },
  { name: '24. 근로소득원천징수영수증(지급명세서)', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '93' },
  { name: '25. 퇴직소득의 범위', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '94' },
  { name: '26. 퇴직소득원천징수영수증(지급명세서)', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '95' },
  { name: '27. 이자.배당소득에 대한 원천징수', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '96' },
  { name: '28. 원천징수영수증(지급명세서)', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '97' },
  { name: '29. 기타소득과 원천징수', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '98' },
  { name: '30. 원천징수영수증(지급명세서)', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '99' },
  { name: '31. 사업소득과 원천징수', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '100' },
  { name: '32. 사업소득원천징수영수증(지급명세서)', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '101' },
  { name: '33. 원천징수의무자', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '102' },
  { name: '34. 원천징수대상소득금액과 원천징수세율', chapter: AM_CHAPTER_CATEGORY.INCOME_TAX_AND_WITHHOLDING_TAX, value: '103' },
  { name: '1. 부가가치세의 의의', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '104' },
  { name: '2. 부가가치세의 계산구조', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '105' },
  { name: '3. 납세의무자', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '106' },
  { name: '4. 납세지', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '107' },
  { name: '5. 과세기간', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '108' },
  { name: '6. 사업자등록', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '109' },
  { name: '7. 부가가치세의 과세대상', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '110' },
  { name: '8. 부수 재화.용역의 공급', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '111' },
  { name: '9. 재화와 용역의 공급시기', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '112' },
  { name: '10. 영세율', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '113' },
  { name: '11. 면세', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '114' },
  { name: '12. 과세표준계산의 일반원칙', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '115' },
  { name: '13. 납부세액의 계산방법', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '116' },
  { name: '14. 매출세액', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '117' },
  { name: '15. 매입세액', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '118' },
  { name: '16. 예정신과와 확정신고', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '119' },
  { name: '17. 부가가치세신고서의 작성', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '120' },
  { name: '18. 결정 및 경정', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '121' },
  { name: '19. 환급', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '122' },
  { name: '20. 국세기본법상 가산세', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '123' },
  { name: '21. 부가가치세법상 가산세', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '124' },
  { name: '22. 세금계산서', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '125' },
  { name: '23. 영수증과 계산서', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '126' },
  { name: '24. 신용카드매출전표와 금전등록기계산서', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '127' },
  { name: '25. 부가가치세의 기장의무', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '128' },
  { name: '26. 세금계산서합계표', chapter: AM_CHAPTER_CATEGORY.VAT_AND_TAX_BILL, value: '129' },
];

const TITLE: MultiSelectorPropTypes['titles'] = ['책', '챕터', '토픽'];

export interface PropTypes {
  values: { book: string; chapter: string; topic: string };
  onChange: MultiSelectorPropTypes['onChanges'];
}

function ChapterForm({ onChange, values }: PropTypes) {
  return <MultiSelector books={BOOKS} chapters={CHAPTER} topics={TOPIC} titles={TITLE} onChanges={onChange} values={values} />;
}

export default ChapterForm;
